# Generated by Django 5.2 on 2025-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='information_images/'),
        ),
    ]
